1.1.1 Создайте двумерный тензор размера (8, 8). Используя как можно меньше операций, добейтесь расстановки кодов "шахматных фигур".

Ожидаемый результат:

[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]

In [1]:
import torch

In [127]:
x_1 = torch.Tensor([[-4, -3, -2, -6, -5, -2, -3, -4],[-1, -1, -1, -1, -1, -1, -1, -1]])
y = torch.empty(4, 8)
y = torch.zeros_like(y)
x_2 = x_1*(-1)
x_2 = torch.flip(x_2,[0,1]).numpy()[:, ::-1]
x_2 = torch.from_numpy(x_2.copy())
s = torch.cat((x_1,y,x_2), 0)
s

tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
        [-1., -1., -1., -1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 4.,  3.,  2.,  6.,  5.,  2.,  3.,  4.]])

## ДЗ

1.1.7 Средствами torch рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

In [47]:
x = torch.arange(2,21,2)
y = torch.arange(3,22,2)
s = x*y
s

tensor([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

1.2.1 Создать тензор размера 11x7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [2]:
import numpy as np

In [95]:
x = [i for i in range(8)]
v = []
for i in range(0,11):
    s = x
    s = [j + 11*i for j in s]
    v.append(s)
v

[[0, 1, 2, 3, 4, 5, 6, 7],
 [11, 12, 13, 14, 15, 16, 17, 18],
 [22, 23, 24, 25, 26, 27, 28, 29],
 [33, 34, 35, 36, 37, 38, 39, 40],
 [44, 45, 46, 47, 48, 49, 50, 51],
 [55, 56, 57, 58, 59, 60, 61, 62],
 [66, 67, 68, 69, 70, 71, 72, 73],
 [77, 78, 79, 80, 81, 82, 83, 84],
 [88, 89, 90, 91, 92, 93, 94, 95],
 [99, 100, 101, 102, 103, 104, 105, 106],
 [110, 111, 112, 113, 114, 115, 116, 117]]

a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])

[[2,2,2],
[2,2,2],
[2,2,2]]

In [145]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]]) 
b_1d = np.array([1,2,3])
s = []
s.append(a_2d[i] - b_1d[i])
print(s)

[array([2, 2, 2]), array([2, 2, 2]), array([2, 2, 2])]


In [148]:
print(a_2d - b_1d.reshape(-1,1))

[[2 2 2]
 [2 2 2]
 [2 2 2]]


a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

array([1,3,5,7])

In [155]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

1.1.4 Написать функцию, которая для целых значений n и m будет возвращать тензор размера nxm, заполненный текстурой размера 2x2, состоящей из следующих значений:

0 1

2 3

In [7]:
x = torch.tensor([[0,1],[2,3]])
def ten(n,m):
    y = torch.tensor([[0, 1], [2, 3]])
    t_y = torch.tile(y, (n, m))
    return t_y
ten(2,2)

tensor([[0, 1, 0, 1],
        [2, 3, 2, 3],
        [0, 1, 0, 1],
        [2, 3, 2, 3]])

1.1.5 Сгенерировать двумерный тензор t размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  ax+b  так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0

In [13]:
x = torch.rand(4,7)
x = (20-0)*x+0
print(x)
x_new = (1/20)*x+0
x_new

tensor([[15.7614, 16.4951, 16.3922,  1.0885,  2.3775, 18.2093, 14.5639],
        [ 8.2095, 10.0985, 19.4443, 15.6159, 11.6326,  2.2232, 11.9859],
        [ 0.5219, 14.5749,  6.5760, 14.5387,  4.2523, 14.6073,  1.4622],
        [13.8701, 14.2547, 11.8234,  7.7719, 15.0496, 15.8834,  1.2095]])


tensor([[0.7881, 0.8248, 0.8196, 0.0544, 0.1189, 0.9105, 0.7282],
        [0.4105, 0.5049, 0.9722, 0.7808, 0.5816, 0.1112, 0.5993],
        [0.0261, 0.7287, 0.3288, 0.7269, 0.2126, 0.7304, 0.0731],
        [0.6935, 0.7127, 0.5912, 0.3886, 0.7525, 0.7942, 0.0605]])

1.1.6 Задать два двумерных тензора ar1 и ar2 размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двумерный тензор размерности (4, 7), каждый элемент которого представляет собой максимум из двух значений, находящихся на аналогичной позиции в массивах ar1, ar2.

In [45]:
ar1 = torch.randint(0,10,(4,7))
ar2 = torch.randint(0,10,(4,7))
print(ar1, ar2)
y = torch.empty(4, 7)
s = []
for i in range(len(ar1)):
    for f, b in zip(ar1[i], ar2[i]):
        s.append(max(f,b))
s = np.array(s)
s1 = torch.from_numpy(s.copy())
s1.reshape(4,7)

tensor([[8, 7, 7, 3, 6, 7, 5],
        [0, 7, 5, 1, 4, 8, 7],
        [7, 9, 0, 9, 9, 5, 9],
        [7, 9, 0, 8, 8, 3, 8]]) tensor([[5, 9, 8, 2, 2, 9, 7],
        [0, 2, 7, 8, 2, 8, 8],
        [5, 1, 8, 7, 7, 0, 3],
        [3, 3, 4, 7, 1, 0, 4]])


tensor([[8, 9, 8, 3, 6, 9, 7],
        [0, 7, 7, 8, 4, 8, 8],
        [7, 9, 8, 9, 9, 5, 9],
        [7, 9, 4, 8, 8, 3, 8]])

1.2.2 Вычесть одномерный тензор b_1d из двухмерного тензора a_2d, так, чтобы каждый элемент одномерного тензора вычитался из всех элементов соответствующих строк двумерного тензора.

In [54]:
b_1d = torch.randint(0,10,(2,))
a_2d = torch.randint(0,10,(5,2))
print(b_1d, a_2d)
s = a_2d-sum(b_1d)
s

tensor([4, 5]) tensor([[7, 9],
        [7, 3],
        [0, 2],
        [3, 2],
        [9, 5]])


tensor([[-2,  0],
        [-2, -6],
        [-9, -7],
        [-6, -7],
        [ 0, -4]])

1.3.3 Из входного тензора a получить только элементы, находящиеся в диапазоне от 5 до 10.

In [59]:
a = torch.randint(0,10,(20,))
print(a)
a[(a>=5)&(a<=10)]

tensor([6, 9, 0, 3, 9, 2, 5, 6, 8, 1, 6, 9, 1, 8, 8, 0, 9, 3, 3, 2])


tensor([6, 9, 9, 5, 6, 8, 6, 9, 8, 8, 9])

1.3.4 Поменять местами столбец 1 и 2 тензора np.arange(9).reshape(3,3)

In [83]:
a = torch.arange(9).reshape(3,3)
print(a)
a_0, a_1 = a[:,0].clone(), a[:,1].clone()
a[:,0] = a_1
a[:,1] = a_0
a

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


tensor([[1, 0, 2],
        [4, 3, 5],
        [7, 6, 8]])

1.3.5 Создать тензор 8 на 10 из случайных целых чисел из диапазона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [11]:
a = torch.randint(0,10,(8,10))
print(a)
a[torch.argmin(torch.sum(a,1))], torch.argmin(torch.sum(a,1))

tensor([[6, 3, 3, 4, 1, 8, 0, 9, 1, 8],
        [3, 4, 6, 4, 0, 5, 8, 4, 4, 9],
        [0, 1, 1, 7, 5, 4, 6, 5, 8, 5],
        [9, 1, 8, 8, 2, 8, 3, 6, 8, 2],
        [8, 0, 0, 6, 9, 7, 3, 1, 6, 0],
        [5, 7, 7, 4, 9, 1, 5, 5, 7, 1],
        [3, 4, 8, 0, 4, 3, 9, 8, 4, 0],
        [7, 3, 4, 9, 9, 3, 6, 4, 7, 5]])


(tensor([8, 0, 0, 6, 9, 7, 3, 1, 6, 0]), tensor(4))

1.3.6 Cоздать тензор из 20 случайных целых чисел от 0 до 100. Обрезать значения тензора (заменить значения, выходящие за диапазон, на крайние значения) снизу по значению 30, сверху по значению 70.

In [18]:
a = torch.randint(0,100,(20,))
print(a)
a = torch.where(a<30,30,a)
a = torch.where(a>70,70,a)
a

tensor([29, 36, 38, 52, 91, 54, 69,  1, 71, 27, 58,  5, 31, 40, 23, 36, 25, 96,
        72, 55])


tensor([30, 36, 38, 52, 70, 54, 69, 30, 70, 30, 58, 30, 31, 40, 30, 36, 30, 70,
        70, 55])

1.3.7 Создать два тензора размера 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первого тензора, которые больше соответсвующих (по расположению) значений второго тензора. Подсчитать сумму этих значений.


In [23]:
ar1 = torch.randint(0,10,(30,3))
ar2 = torch.randint(0,10,(30,3))
sum(sum(torch.where(ar1>ar2,ar1,0)))

tensor(237)

1.3.8 При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.


In [29]:
ar1 = torch.randint(0,10,(20,20))
print(ar1)
ind = np.arange(19)
ar1[ind,ind+1]

tensor([[4, 1, 6, 5, 2, 3, 6, 8, 7, 8, 0, 7, 1, 9, 7, 1, 3, 7, 7, 2],
        [3, 4, 4, 8, 1, 9, 3, 6, 7, 8, 4, 9, 7, 6, 2, 3, 4, 5, 3, 1],
        [0, 2, 3, 7, 8, 1, 4, 2, 9, 2, 3, 9, 0, 4, 3, 3, 4, 3, 6, 1],
        [5, 1, 0, 8, 1, 7, 0, 0, 2, 6, 1, 9, 7, 3, 5, 3, 3, 0, 0, 1],
        [2, 2, 5, 7, 1, 6, 9, 6, 8, 2, 3, 0, 8, 5, 6, 2, 3, 7, 5, 5],
        [5, 9, 2, 7, 5, 0, 4, 2, 6, 6, 1, 6, 2, 0, 4, 2, 7, 9, 0, 8],
        [0, 8, 6, 5, 1, 7, 2, 1, 7, 8, 5, 4, 9, 4, 5, 8, 6, 2, 0, 8],
        [4, 8, 0, 9, 3, 9, 3, 2, 0, 4, 8, 9, 2, 7, 7, 6, 8, 3, 9, 4],
        [8, 3, 7, 1, 2, 5, 5, 0, 7, 0, 8, 6, 2, 8, 7, 6, 2, 9, 8, 8],
        [9, 0, 9, 9, 1, 1, 2, 3, 4, 7, 4, 5, 4, 1, 7, 4, 8, 5, 6, 3],
        [5, 9, 9, 9, 7, 4, 6, 2, 3, 4, 8, 5, 9, 2, 0, 5, 1, 6, 7, 6],
        [9, 2, 0, 4, 7, 7, 2, 3, 2, 1, 7, 3, 0, 9, 0, 5, 7, 1, 6, 2],
        [6, 3, 6, 8, 2, 0, 7, 7, 6, 2, 7, 1, 4, 3, 7, 3, 0, 9, 4, 4],
        [2, 3, 2, 3, 6, 2, 7, 0, 3, 7, 3, 6, 6, 7, 3, 1, 6, 9, 5, 7],
        [2, 4, 1, 9,

tensor([1, 4, 7, 1, 6, 4, 1, 0, 0, 4, 5, 0, 3, 3, 7, 0, 9, 6, 2])

1.3.9 Задать два двухмерных тензора ar1 и ar2 размерности (5, 10), состоящих из случайных целых чисел в пределах от 0 до 10. Удвоить все значения ar1, которые совпадают со значениями ar2, расположенными на аналогичных позициях.

In [30]:
ar1 = torch.randint(0,10,(5,10))
ar2 = torch.randint(0,10,(5,10))
torch.where(ar1==ar2,2*ar1,ar1)

tensor([[ 2,  8,  5,  4,  4,  8,  0, 14,  3,  8],
        [14,  9,  0,  7,  6,  2,  6,  3,  3,  1],
        [ 4,  4,  2,  5,  2,  9,  8,  7,  6,  1],
        [ 2,  2,  8,  5,  5,  0,  1,  0,  7,  2],
        [ 3, 16,  8,  3,  5,  7,  7,  7,  3,  2]])

1.3.10 Заданы три двухмерных тензора ar1, ar2 и ar3 размерности (4, 7), состоящие из случайных целых чисел в пределах от 0 до 10. Обнулить все элементы ar1, которые больше соответствующих (находящихся в соответствующих позициях) элементов ar2 и меньше соответствующих элементов ar3.

In [35]:
ar1 = torch.randint(0,10,(4,7))
ar2 = torch.randint(0,10,(4,7))
ar3 = torch.randint(0,10,(4,7))
print(ar1,ar2,ar3)
torch.where((ar1>ar2)&(ar1<ar3),0,ar1)

tensor([[9, 3, 1, 1, 5, 9, 1],
        [4, 0, 4, 0, 3, 7, 3],
        [4, 4, 3, 8, 6, 1, 2],
        [6, 8, 2, 9, 0, 3, 9]]) tensor([[8, 7, 8, 1, 9, 1, 0],
        [0, 2, 2, 8, 2, 0, 0],
        [2, 2, 3, 3, 5, 8, 9],
        [7, 6, 5, 2, 5, 0, 8]]) tensor([[4, 8, 7, 1, 1, 4, 1],
        [7, 7, 1, 8, 0, 8, 1],
        [7, 8, 7, 5, 0, 5, 6],
        [4, 2, 2, 3, 9, 5, 1]])


tensor([[9, 3, 1, 1, 5, 9, 1],
        [0, 0, 4, 0, 3, 0, 3],
        [0, 0, 3, 8, 6, 1, 2],
        [6, 8, 2, 9, 0, 0, 9]])

1.3.11 Задан двумерный тензор ar1 размерности (20, 5), состоящий из случайных целых чисел в пределах от 0 до 20. Определить, в каких столбцах не менее 5 раз встречается значение, максимальное по своей строке.

In [46]:
ar1 = torch.randint(0,20,(20,5))
print(ar1)
mx = torch.argmax(ar1,1)
print(mx)
uniques, counts = torch.unique(mx, return_counts = True)
print(uniques, counts)
uniques[torch.where(counts>=5)]

tensor([[16,  6, 19, 17,  9],
        [ 4,  6, 16, 14, 11],
        [ 4,  2, 14,  7,  2],
        [14,  1, 14, 17,  2],
        [15, 10, 18,  1, 12],
        [17,  5,  4, 10,  5],
        [13, 11, 17, 19,  3],
        [ 1, 12, 19,  1,  1],
        [ 0, 10, 17,  5,  0],
        [ 5, 13,  6,  3, 10],
        [12, 16,  9, 17,  5],
        [ 3, 10,  7,  2, 14],
        [ 1,  9,  2, 14,  0],
        [15,  4, 19, 10, 15],
        [ 6,  5, 16, 18, 11],
        [11, 13,  2, 18,  0],
        [12, 11, 11,  4,  7],
        [ 8,  1, 10,  8, 11],
        [13, 14,  1, 12,  7],
        [16,  7, 16, 16,  2]])
tensor([2, 2, 2, 3, 2, 0, 3, 2, 2, 1, 3, 4, 3, 2, 3, 3, 0, 4, 1, 0])
tensor([0, 1, 2, 3, 4]) tensor([3, 2, 7, 6, 2])


tensor([2, 3])

1.3.12 Задан двумерный тензор ar1 размерности (4, 7), состоящий из случайных чисел в пределах от 0 до 1. Обнулить все значения в массиве, расположенные строго правее и ниже максимального элемента массива.

In [79]:
ar1 = torch.rand(4,7)
print(ar1)
ind = (ar1 == torch.flatten(ar1)[torch.argmax(ar1)]).nonzero(as_tuple=True)
print(ar1[ind])
ar1[ind[0]+1:] = 0
ar1[:,ind[1]+1:] = 0
ar1

tensor([[0.1876, 0.7960, 0.2471, 0.2828, 0.1053, 0.4936, 0.4922],
        [0.4113, 0.8767, 0.9670, 0.0236, 0.9964, 0.2442, 0.5369],
        [0.8474, 0.3120, 0.7372, 0.6194, 0.6088, 0.1841, 0.2737],
        [0.3906, 0.2261, 0.3828, 0.0022, 0.6458, 0.1380, 0.8246]])
tensor([0.9964])


tensor([[0.1876, 0.7960, 0.2471, 0.2828, 0.1053, 0.0000, 0.0000],
        [0.4113, 0.8767, 0.9670, 0.0236, 0.9964, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])

1.3.13 Построить "one-hot encoding" для одномерного тензора, содержащего целые числа (длина вектора заранее неизвестна, набор значений заранее неизвестен, при этом в итоговой матрице должны присутствовать столбцы для всех натуральных чисел вплоть до максимального встречающегося в исходном массиве).

In [86]:
ar1 = torch.randint(0,20,(20,))
print(ar1)
def one_hot_encoding(tensor):
    max_num = max(tensor)
    nums = range(max_num + 1)

    result = np.zeros((len(tensor), len(nums)))

    for i in range(len(tensor)):
        result[i][int(tensor[i])] = 1

    return result

one_hot_encoding(ar1)

tensor([14,  2,  5,  4,  6, 18,  6,  7, 14,  6, 13,  1,  4,  7,  6,  6,  1, 19,
        14,  2])


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.